export const EXPERTISE = [
  {
    icon: "brain",
    alt: "Brain icon",
    title: "AGENTIC AI SYSTEMS",
    body: "I build the end-to-end systems that let LLMs autonomously analyze, refactor, and execute against large codebases: transport, runtime, retrieval, and the agent loop itself. Four production agent systems shipped to date.",
    dim: "32px",
    color: "#3F3F46",
  },
  {
    icon: "cog",
    alt: "Cog icon",
    title: "MCP & TOOL ORCHESTRATION",
    body: "I built a Model Context Protocol client top to bottom: JSON-RPC 2.0 over stdio/HTTP/SSE, multi-server management, OAuth 2.1, health-checked reconnect, and on-demand tool-schema discovery to keep context windows lean.",
    dim: "32px",
    color: "#3F3F46",
  },
  {
    icon: "security",
    alt: "Shield icon",
    title: "AI SECURITY & RED-TEAMING",
    body: "I close agent-tool-execution vulnerabilities like prompt injection, command injection, subshell bypass, SSRF, secret storage, and OAuth, across multi-round adversarial reviews, and research a formal taxonomy of agentic-AI risk at Ontario Tech.",
    dim: "32px",
    color: "#3F3F46",
  },
  {
    icon: "computer",
    alt: "Computer icon",
    title: "CONTEXT ENGINEERING",
    body: "I engineer what the model sees: prompt-cache layout, deferred tool-schema loading, scoped compaction protection, recency-biased retrieval, and injection budgets tuned against recall for long-running agent workflows.",
    dim: "28px",
    color: "#3F3F46",
  },
  {
    icon: "server",
    alt: "Server icon",
    title: "DISTRIBUTED BACKENDS",
    body: "Years shipping production services: high-throughput healthcare claims (EDI 837, C#/EF), Django/DRF platforms, async pipelines, and the semantic-memory infrastructure behind multi-step agents. Docker, AWS, PostgreSQL.",
    dim: "24px",
    color: "#3F3F46",
  },
  {
    icon: "brush",
    alt: "Research icon",
    title: "APPLIED RESEARCH",
    body: "Peer-reviewed work on adversarial machine learning (PST 2025) and a MITACS-funded project architecting MCP-enabled agent infrastructure. I read the literature, prototype the defense, and ship it.",
    dim: "24px",
    color: "#3F3F46",
  },
];
