export const EXPERTISE = [
  {
    icon: "security",
    alt: "Shield icon",
    title: "CYBERSECURITY",
    body: "I conduct vulnerability assessments, use tools like Nmap, Wireshark, and Burp Suite, and apply OWASP principles. I script network scans, automate reports, and implement basic intrusion detection.",
    dim: "32px",
    color: "#3F3F46",
  },
  {
    icon: "brain",
    alt: "Brain icon",
    title: "MACHINE LEARNING",
    body: "I build, train, and evaluate ML models using Python (scikit-learn, PyTorch). I specialize in anomaly detection, backdoor defenses, and explainable AI in production-grade pipelines.",
    dim: "32px",
    color: "#3F3F46",
  },
  {
    icon: "server",
    alt: "Server icon",
    title: "DevOps & CLOUD",
    body: "I manage Linux-based servers (Debian/Ubuntu), automate CI/CD pipelines with GitHub Actions, and deploy applications using Docker and AWS (EC2, S3, Route 53, Lambda).",
    dim: "24px",
    color: "#3F3F46",
  },
  {
    icon: "computer",
    alt: "Computer icon",
    title: "FRONT-END",
    body: "I craft responsive, fast, and accessible UIs using React JS, Next.js, and Tailwind CSS. I'm skilled in component-driven development and modern state management tools like Redux Toolkit.",
    dim: "28px",
    color: "#3F3F46",
  },
  {
    icon: "cog",
    alt: "Cog icon",
    title: "BACK-END",
    body: "I develop scalable APIs and web services using Django Rest Framework and Node.js. I have experience with PostgreSQL, MongoDB, and authentication mechanisms such as JWT and OAuth.",
    dim: "32px",
    color: "#3F3F46",
  },
  {
    icon: "brush",
    alt: "Paint brush icon",
    title: "UI/UX DESIGN",
    body: "I create user-focused web and mobile designs using Figma. I prototype, iterate, and deliver polished visuals with an emphasis on usability and accessibility standards.",
    dim: "24px",
    color: "#3F3F46",
  },
];
