import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import AboutProvider from "@/context/AboutContext/AboutContext";
import ThemeProvider from "@/context/ThemeContext/ThemeContext";
import ContactProvider from "@/context/ContactContext/ContactContext";
import ProjectProvider from "@/context/ProjectContext/ProjectContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider>
          <ProjectProvider>
            <ContactProvider>
              <AboutProvider>{children}</AboutProvider>
            </ContactProvider>
          </ProjectProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
