import "./globals.css";
import type { Metadata } from "next";
import { koho, bungee } from "@/fonts";

export const metadata: Metadata = {
  title: "Home - Edolor",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${koho.variable} ${bungee.variable} font-sans`}>
        {children}
      </body>
    </html>
  );
}
